In [1]:
#Numpy(can handle multi-dimension array and matrices)
#Large collection of mathemetical function to operate on these arrays.

In [5]:
import time
import numpy as np

size_of_vac=10000000
def pure_python_version():
    time_python=time.time()
    my_list1=range(size_of_vac)
    my_list2=range(size_of_vac)
    sum_list=[my_list1[i]+my_list2[i] for i in range(len(my_list1))]
    return time.time()-time_python

def numpy_version():
    time_numpy=time.time()
    my_arr1=np.arange(size_of_vac)
    my_arr2=np.arange(size_of_vac)
    sum_array=my_arr1+my_arr2
    return time.time()-time_numpy

python_time=pure_python_version()
numpy_time=numpy_version()
print("pure pythin version{:0.4f}".format(python_time))
print("Numpy version{:0.4f}".format(numpy_time))
print("Numpy is in this example{:0.4f} times faster!".format(python_time/numpy_time))

pure pythin version5.9033
Numpy version0.1070
Numpy is in this example55.1682 times faster!


In [13]:
#Creating numpy arrays

my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [14]:
type(my_list)

list

In [15]:
arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [22]:
type(arr)

numpy.ndarray

In [16]:
my_mat=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]   #Creating 2d list or list of lists

In [17]:
mat=np.array(my_mat)    #this is 2d array
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
type(mat)

numpy.ndarray

In [19]:
arr.shape      #this gives the shape of the array

(5,)

In [20]:
mat.shape         #This gives the number of rows and columns of the array

(4, 3)

In [21]:
arr.ndim          #This is 1D array

1

In [22]:
mat.ndim     #2d array or matrix
#ndim function is for checking dimension

2

In [23]:
arr.dtype                 #the datatype of element inside the array

dtype('int32')

In [24]:
mat.dtype

dtype('int32')

In [25]:
#ARRAY INITIALIZATION
np.arange(0,10)     #no step size

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10,2) #step sizw two

array([0, 2, 4, 6, 8])

In [27]:
np.zeros(4)  #Generate a numpy array of 4 zeros

array([0., 0., 0., 0.])

In [28]:
np.zeros((3,3))       #generate a 3*3 null matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,3))       #filled with 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,5,10)      #Generate 10 points between 0 to 5.
#linspace is used for making high resolution plots

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.eye(3)  #generate identity matrix of size 3*3(this is used in singular value decomposition)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#Array Intitialization using Random Numbers
#In various application like assigning weights in Artificial Neural Network,arrays need to be initialised randomly
np.random.rand(5)

array([0.84413067, 0.36554383, 0.61015327, 0.46012475, 0.28597643])

In [34]:
np.random.rand(2,2)         #generate 2D matrix where elements are random

array([[0.62749425, 0.5597809 ],
       [0.19773732, 0.89624895]])

In [35]:
np.random.rand(4,4)         #4D matrix with random elements

array([[0.42492448, 0.91128659, 0.15493297, 0.13238095],
       [0.3596375 , 0.94569989, 0.66768661, 0.35515104],
       [0.85090266, 0.64818081, 0.01886689, 0.53886039],
       [0.66525888, 0.52362749, 0.38902039, 0.80743398]])

In [37]:
np.random.rand(9).reshape(3,3)

array([[0.63017012, 0.57312929, 0.00176919],
       [0.19133914, 0.95897253, 0.64461146],
       [0.13193312, 0.09121514, 0.87779325]])

In [39]:
#Numpy indexing
my_arr=np.arange(0,11)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
my_arr[3]

3

In [41]:
#Arrays Slicing
my_arr[1:5]    #It will return all the elements between 1 and 5 excluding 5

array([1, 2, 3, 4])

In [42]:
my_arr[8:]         #It will return all the element from index 8 and beyond

array([ 8,  9, 10])

In [43]:
my_arr[:6]         #It will return all element from first index to 5

array([0, 1, 2, 3, 4, 5])

In [44]:
my_arr[0:5]=-3         #Numpy arrays are mutable
my_arr

array([-3, -3, -3, -3, -3,  5,  6,  7,  8,  9, 10])

In [45]:
arr_2d=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])     #creating 2D array
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
arr_2d[0][2]   #throws 0th row and 2nd column element

2

In [47]:
arr_2d[0:2,0:2]     #Elements in row 0 and 1 and column 0 and 1

array([[0, 1],
       [3, 4]])

In [49]:
arr_2d[:2,1:]     #Elements from rows 0 and 1 and column 1 and 2

array([[1, 2],
       [4, 5]])

In [11]:
#Conditional Indexing in Array
arr_cond=np.arange(0,11)
arr_cond>5             #this will return a boolean array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [12]:
bool_arr=arr_cond<5
arr_cond[bool_arr]         #this will return all the element of an array where element size>5     

array([0, 1, 2, 3, 4])

In [13]:
bool_arr=arr_cond>5
arr_cond[bool_arr]

array([ 6,  7,  8,  9, 10])

In [14]:
arr_cond[arr_cond<5]  #this is the same thing without using another object.

array([0, 1, 2, 3, 4])

In [8]:
#Numpy broadcasting
#Rule
#If two dimension are equal,you can continue
#If one of the operand is 1, stretch it to match the largest one

In [10]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])     #Creating Numpy array
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
arr_2d.shape

(4, 3)

In [17]:
scaler=3           #scaler
arr_1d=np.array([10,10,10])        #array with different shape

In [18]:
arr_1d.shape

(3,)

In [19]:
arr_2d+scaler

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
arr_2d+arr_1d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [22]:
arr=np.array([[1,1,1,1]])
arr_2d+arr                     #throws an exception if dimensions doesn't match

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [25]:
#Numpy mathematical Function
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr.min()

1

In [28]:
arr.max()          #min and max are used to calculate the range of an array

10

In [29]:
arr.argmin()          #Index position of min and max element

0

In [30]:
arr.argmax()          #Argmax can be used to observe the output of softmax layer Neural Network

9

In [31]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [33]:
arr.mean()          #Missing value of the column can be replaced by the mean of that column in some dataset

5.5

In [34]:
np.exp(arr)      #To calculate exponentioal value/Expo function is used in Activation Function of Neural Network

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [35]:
#Array Manipulation(Change the Sturcture and shape of an array)

In [41]:
#Reshape Function
arr=np.arange(0,16)
arr_2d=arr.reshape(4,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#Flatten Function
arr_2d.flatten()            #This is used in convolutional neural network to flatten a 2D image mto individual pixels

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
#Transpose Function
arr_2d.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [51]:
#Merging and Splitting an array
arr_x=np.array([[1,2,3,4],[5,6,7,8]])      #Lets create 2 arrays
arr_y=np.array([[21,22,23,24],[25,26,27,28]])

In [56]:
arr_z=np.concatenate((arr_x,arr_y),axis=0)  #Join 2 arrays along rows/use to add new features in dataset
arr_z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [57]:
#Horizontal Split
np.hsplit(arr_z,2)

[array([[ 1,  2],
        [ 5,  6],
        [21, 22],
        [25, 26]]),
 array([[ 3,  4],
        [ 7,  8],
        [23, 24],
        [27, 28]])]

In [59]:
#Vertical Split
np.vsplit(arr_z,2)             #vertical split can be used in cross validation in machine learning

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]